"""Dataset discovery and loading: `data/manifest.yaml` + CSV files.

Name datasets are normalized CSVs checked in under `data/` (regenerated by
`scripts/generate_name_data.py` from the names-dataset pickles). Everything
is still normalized on read: fields stripped, blank lines skipped, and any
malformed row fails loudly with the file name and line number.
"""

from __future__ import annotations

import functools
from bisect import bisect_left, bisect_right
from importlib import resources

import yaml

from .models import Gender, NameEntry, OriginProfile

_DATA = resources.files("golemorph").joinpath("data")


@functools.cache
def load_manifest() -> dict:
    """Raw `origins` mapping from `data/manifest.yaml`."""
    with _DATA.joinpath("manifest.yaml").open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)["origins"]


@functools.cache
def load_origin(code: str) -> OriginProfile:
    """Build the :class:`OriginProfile` declared in the manifest for `code`."""
    origins = load_manifest()
    code = code.upper()
    try:
        entry = origins[code]
    except KeyError:
        valid = ", ".join(sorted(origins))
        raise ValueError(f"unknown origin {code!r} - valid codes: {valid}") from None
    first = entry["datasets"]["first_names"]
    last = entry["datasets"]["surnames"]
    return OriginProfile(
        code=code,
        label=entry["label"],
        language=entry["language"],
        nationality=entry["nationality"],
        region=entry["region"],
        name_order=entry["name_order"],
        dial_code=str(entry["dial_code"]),
        phone_format=entry["phone_format"],
        subscriber_digits=int(entry["subscriber_digits"]),
        mobile_prefixes=tuple(str(p) for p in entry["mobile_prefixes"]),
        email_domains=tuple(entry["email_domains"]),
        cities=tuple(entry["cities"]),
        roles=tuple(entry["roles"]),
        first_names_file=first["file"],
        first_names_source=first["source"],
        surnames_file=last["file"],
        surnames_source=last["source"],
        gendered_surnames=bool(entry.get("gendered_surnames", False)),
    )



def origins() -> list[OriginProfile]:
    """All shipped origin profiles, sorted by code."""
    return sorted(
        (load_origin(code) for code in load_manifest()), key=lambda p: p.code
    )


def _with_percentiles(entries: list[NameEntry]) -> tuple[NameEntry, ...]:
    """Attach each entry's percentile rank (0-100) within its dataset."""
    from dataclasses import replace

    freqs = sorted(e.frequency for e in entries)
    total = len(freqs)
    scored = []
    for entry in entries:
        lower = bisect_left(freqs, entry.frequency)
        equal = bisect_right(freqs, entry.frequency) - lower
        percentile = 100.0 * (lower + 0.5 * equal) / total
        scored.append(replace(entry, percentile=round(percentile, 1)))
    return tuple(scored)


def _single_token(name: str) -> str:
    """Fold a name to one token: `"El idrissi"` -> `"Elidrissi"`.

    Datasets can carry a compound spelling with an inner space alongside its
    single-token twin, so every key is folded before merging - otherwise one
    family would be drawn under two spellings at half its real weight.
    """
    return "".join(name.split()).lower()


def _read_rows(filename: str) -> list[tuple[str, str]]:
    """Read `<file>.csv` beyond its header, skipping blank lines."""
    # Manifest paths are "<CODE>/FirstName.csv"; split so joinpath works on
    # every importlib.resources backend, not just a plain directory.
    text = _DATA.joinpath(*filename.split("/")).read_text(encoding="utf-8")
    rows = []
    for lineno, line in enumerate(text.splitlines()[1:], start=2):
        if not line.strip():
            continue  # tolerate stray blank lines
        rows.append((line, lineno))
    return rows


@functools.cache
def _all_first_names(code: str) -> tuple[NameEntry, ...]:
    profile = load_origin(code)
    entries = []
    for line, lineno in _read_rows(profile.first_names_file):
        parts = [part.strip() for part in line.rsplit(",", 2)]
        if len(parts) != 3:
            raise ValueError(
                f"{profile.first_names_file}:{lineno}: expected name,gender,"
                f"frequency, got {line!r}"
            )
        name, gender, frequency = parts
        try:
            count = int(frequency)
        except ValueError:
            raise ValueError(
                f"{profile.first_names_file}:{lineno}: invalid frequency "
                f"{frequency!r} for {name!r}"
            ) from None
        entries.append(
            NameEntry(name, count, Gender(gender) if gender else None)
        )
    return _with_percentiles(entries)


@functools.cache
def _all_surnames(code: str) -> tuple[NameEntry, ...]:
    profile = load_origin(code)
    # Merge duplicate spellings of one family (`El idrissi` + `Elidrissi`)
    # under a single space-free key so their frequencies sum - otherwise one
    # family would be drawn under two spellings at half its real weight. The
    # *displayed* name stays a real spelling from the source: the most
    # frequent raw spelling of the merged group wins, and a family with no
    # twin keeps its own spelling (`El mostafa` stays `El mostafa`).
    totals: dict[tuple[str, Gender | None], dict] = {}
    for line, lineno in _read_rows(profile.surnames_file):
        parts = [part.strip() for part in line.rsplit(",", 1)]
        if len(parts) != 2:
            raise ValueError(
                f"{profile.surnames_file}:{lineno}: expected name,frequency, "
                f"got {line!r}"
            )
        raw_name, frequency = parts
        try:
            count = int(frequency)
        except ValueError:
            raise ValueError(
                f"{profile.surnames_file}:{lineno}: invalid frequency "
                f"{frequency!r} for {raw_name!r}"
            ) from None
        # Tag gendered surname forms (Russian Ivanov/Ivanova) so the sampler
        # can pick the variant matching the persona's gender. The RUS dataset
        # is in Cyrillic, where the feminine suffix is `а` - accept both.
        gender = None
        if profile.gendered_surnames:
            gender = (
                Gender.FEMALE
                if raw_name.lower().endswith(("a", "а"))
                else Gender.MALE
            )
        key = (_single_token(raw_name), gender)
        slot = totals.setdefault(
            key, {"name": raw_name, "count": 0, "best": 0}
        )
        slot["count"] += count
        # Display the most frequent raw spelling of the merged group.
        if count > slot["best"]:
            slot["best"] = count
            slot["name"] = raw_name
    entries = [
        NameEntry(slot["name"], slot["count"], key[1])
        for key, slot in totals.items()
    ]
    return _with_percentiles(entries)


def load_first_names(code: str, gender: Gender | None = None) -> tuple[NameEntry, ...]:
    """Given names for `code`, optionally restricted to one gender."""
    return gender_compatible(_all_first_names(code), gender)


def load_surnames(code: str, gender: Gender | None = None) -> tuple[NameEntry, ...]:
    """Surnames for `code`; gendered locales keep only matching variants."""
    return gender_compatible(_all_surnames(code), gender)


def gender_compatible(
    entries: tuple[NameEntry, ...], gender: Gender | None
) -> tuple[NameEntry, ...]:
    """Entries usable for `gender`: neutral ones plus those matching it."""
    if gender is None:
        return tuple(entries)
    return tuple(e for e in entries if e.gender in (None, gender))
